version: '3'

services: 
    app:
        container_name: laravel
        entrypoint: dockerize -template ./docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./docker/entrypoint.sh
        image: ferreirafernandar/laravel-docker:latest
        volumes:
            - .:/var/www
        networks:
            - app-network  
        depends_on:
            - db
            - redis
        environment:
            - _DB_HOST=db
            - _DB_DATABASE=laravel-docker
            - _DB_USERNAME=root
            - _DB_PASSWORD=root         
     
    nginx:
        image: ferreirafernandar/nginx-dockerize:latest
        container_name: nginx
        entrypoint: " dockerize -template /etc/nginx/template/nginx.conf:/etc/nginx/conf.d/default.conf -wait tcp://app:9000 -timeout 40s /docker-entrypoint.sh"
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/template:/etc/nginx/template
        networks:
            - app-network
        depends_on:
            - app    
        environment:
            - NGINX_ROOT=/var/www/html/public
            - NGINX_HOST=localhost
            - NGINX_PORT=80
    db:
        build: ./docker/mysql
        container_name: mysql
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./docker/data:/var/lib/mysql
        networks:
            - app-network  
        environment:
            - MYSQL_DATABASE=laravel-docker
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root   

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"          
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
